# Generated by Django 4.2.18 on 2025-02-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
    ]
