# Generated by Django 4.2.18 on 2025-02-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_teacher_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=35)),
                ('text2', models.CharField(max_length=35)),
                ('text3', models.CharField(max_length=35)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
